// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransportCompany.DAL;

#nullable disable

namespace TransportCompany.DAL.Migrations
{
    [DbContext(typeof(TransportCompanyContext))]
    [Migration("20221127235430_TestMigration")]
    partial class TestMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TransportCompany.Domain.Entities.Driver", b =>
                {
                    b.Property<string>("Driver_license_number")
                        .HasColumnType("char(10)");

                    b.Property<string>("Addres")
                        .IsRequired()
                        .HasMaxLength(155)
                        .HasColumnType("nvarchar(155)");

                    b.Property<string>("Driver_license_category")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("FIO")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(155)
                        .HasColumnType("nvarchar(155)");

                    b.Property<string>("Phone_number")
                        .IsRequired()
                        .HasColumnType("char(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Year_of_start_work")
                        .IsRequired()
                        .HasColumnType("char(4)");

                    b.HasKey("Driver_license_number");

                    b.ToTable("Driver");
                });

            modelBuilder.Entity("TransportCompany.Domain.Entities.Product", b =>
                {
                    b.Property<string>("Сatalogue_number")
                        .HasColumnType("char(35)");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("RequestNumber")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Сatalogue_number");

                    b.HasIndex("RequestNumber");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("TransportCompany.Domain.Entities.Product_exmp", b =>
                {
                    b.Property<int>("Storage_number")
                        .HasColumnType("int");

                    b.Property<string>("Сatalogue_number")
                        .HasColumnType("char(35)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.HasKey("Storage_number", "Сatalogue_number");

                    b.HasIndex("Сatalogue_number");

                    b.ToTable("Product_exmp");
                });

            modelBuilder.Entity("TransportCompany.Domain.Entities.Requare_product", b =>
                {
                    b.Property<int>("RequestID")
                        .HasColumnType("int");

                    b.Property<string>("Сatalogue_number")
                        .HasColumnType("char(35)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.HasKey("RequestID", "Сatalogue_number");

                    b.HasIndex("Сatalogue_number");

                    b.ToTable("Requare_product");
                });

            modelBuilder.Entity("TransportCompany.Domain.Entities.Request", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Number"), 1L, 1);

                    b.Property<int>("Car_load")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date_dispatch")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Delivery_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverID")
                        .IsRequired()
                        .HasColumnType("char(10)");

                    b.Property<int>("Num_Receiving_storage")
                        .HasColumnType("int");

                    b.Property<int>("Num_Sending_storage")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<int>("Total_cost")
                        .HasColumnType("int");

                    b.Property<int>("Total_length")
                        .HasColumnType("int");

                    b.Property<int>("Total_mass")
                        .HasColumnType("int");

                    b.Property<int>("Total_shipping_cost")
                        .HasColumnType("int");

                    b.Property<int>("Total_time")
                        .HasColumnType("int");

                    b.Property<string>("VehicleID")
                        .IsRequired()
                        .HasColumnType("char(17)");

                    b.HasKey("Number");

                    b.HasIndex("DriverID");

                    b.HasIndex("VehicleID");

                    b.ToTable("Request");

                    b.HasCheckConstraint("Number", "Number > 0");
                });

            modelBuilder.Entity("TransportCompany.Domain.Entities.Storage", b =>
                {
                    b.Property<int>("Storage_number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Storage_number"), 1L, 1);

                    b.Property<string>("Addres")
                        .IsRequired()
                        .HasMaxLength(155)
                        .HasColumnType("nvarchar(155)");

                    b.Property<string>("FIO_manager")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone_number")
                        .IsRequired()
                        .HasColumnType("char(10)");

                    b.Property<string>("Requests")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Storage_number");

                    b.ToTable("Storage");
                });

            modelBuilder.Entity("TransportCompany.Domain.Entities.Transport_vehicle", b =>
                {
                    b.Property<string>("Vehicle_identification_number")
                        .HasColumnType("char(17)");

                    b.Property<float>("Fuel_consumption")
                        .HasColumnType("real");

                    b.Property<int>("Load_capacity")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(155)
                        .HasColumnType("nvarchar(155)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Required_category")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<int>("Transported_volume")
                        .HasColumnType("int");

                    b.HasKey("Vehicle_identification_number");

                    b.ToTable("Transport_vehicle");
                });

            modelBuilder.Entity("TransportCompany.Domain.Entities.Product", b =>
                {
                    b.HasOne("TransportCompany.Domain.Entities.Request", null)
                        .WithMany("Products")
                        .HasForeignKey("RequestNumber");
                });

            modelBuilder.Entity("TransportCompany.Domain.Entities.Product_exmp", b =>
                {
                    b.HasOne("TransportCompany.Domain.Entities.Storage", "Storage")
                        .WithMany("Product_Exmps")
                        .HasForeignKey("Storage_number")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransportCompany.Domain.Entities.Product", "Product")
                        .WithMany("Product_Exmps")
                        .HasForeignKey("Сatalogue_number")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Storage");
                });

            modelBuilder.Entity("TransportCompany.Domain.Entities.Requare_product", b =>
                {
                    b.HasOne("TransportCompany.Domain.Entities.Request", "Request")
                        .WithMany("Requare_Products")
                        .HasForeignKey("RequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransportCompany.Domain.Entities.Product", "Product")
                        .WithMany("Requare_Products")
                        .HasForeignKey("Сatalogue_number")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("TransportCompany.Domain.Entities.Request", b =>
                {
                    b.HasOne("TransportCompany.Domain.Entities.Driver", "Driver")
                        .WithMany("Requests")
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransportCompany.Domain.Entities.Transport_vehicle", "vehicle")
                        .WithMany("Requests")
                        .HasForeignKey("VehicleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("vehicle");
                });

            modelBuilder.Entity("TransportCompany.Domain.Entities.Driver", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("TransportCompany.Domain.Entities.Product", b =>
                {
                    b.Navigation("Product_Exmps");

                    b.Navigation("Requare_Products");
                });

            modelBuilder.Entity("TransportCompany.Domain.Entities.Request", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Requare_Products");
                });

            modelBuilder.Entity("TransportCompany.Domain.Entities.Storage", b =>
                {
                    b.Navigation("Product_Exmps");
                });

            modelBuilder.Entity("TransportCompany.Domain.Entities.Transport_vehicle", b =>
                {
                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
